# Generated by Django 3.0.5 on 2020-10-31 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('npk', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='NIK tidak valid', message='Hanya Angka', regex='^[0-9]*$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
