# Generated by Django 3.0.5 on 2020-10-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=30)),
                ('jam_masuk', models.DateTimeField()),
                ('jam_keluar', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi_apps.Kategori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akun.Profil')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_jam', models.DateTimeField(auto_now_add=True)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='absensi_apps.Peserta')),
            ],
        ),
    ]
